// ── Meta Comment Rule ────────────────────────────────────
// Detects AI attribution comments that should not be in committed code.

import type { Diagnostic } from '../../../types/index.js'
import { diag } from '../shared.js'

const META_COMMENT_PATTERNS = [
  /\/\/\s*Generated\s+by/i,
  /\/\/\s*AI[- ]?assisted/i,
  /\/\/\s*Created\s+with\s+(?:Claude|GPT|ChatGPT|Copilot|Gemini|AI)/i,
  /\/\/\s*Auto[- ]?generated/i,
  /\/\/\s*Written\s+by\s+(?:Claude|GPT|ChatGPT|Copilot|Gemini|AI)/i,
  /\/\*\s*Generated\s+by/i,
  /\/\*\s*AI[- ]?assisted/i,
  /\/\*\s*Auto[- ]?generated/i,
  /#\s*Generated\s+by/i,
  /#\s*AI[- ]?assisted/i,
  /#\s*Auto[- ]?generated/i,
  /#\s*Created\s+with\s+(?:Claude|GPT|ChatGPT|Copilot|Gemini|AI)/i,
]

export function detectMetaComment(
  lines: { num: number; text: string }[],
  filePath: string,
): Diagnostic[] {
  const results: Diagnostic[] = []

  for (const { num, text } of lines) {
    const trimmed = text.trim()
    for (const pattern of META_COMMENT_PATTERNS) {
      if (pattern.test(trimmed)) {
        const col = text.indexOf(trimmed.charAt(0)) + 1
        const label = trimmed.match(/(Generated by|AI.assisted|Created with|Auto.generated|Written by)/i)?.[1] ?? 'AI attribution'
        results.push(
          diag({
            filePath,
            rule: 'ast-slop/meta-comment',
            severity: 'info',
            message: `AI attribution comment: "${label}" — metadata that should not be in committed code`,
            help: 'Remove AI attribution comments. Use git history or .ai-metadata files if tracking is needed. These comments add noise and reveal tooling choices.',
            line: num,
            column: col,
            fixable: true,
            suggestion: {
              type: 'delete',
              text: '',
              range: { startLine: num, startCol: 1, endLine: num, endCol: text.length + 1 },
              confidence: 0.95,
              reason: 'AI attribution comments are metadata noise that should not be in committed source code.',
            },
          }),
        )
        break
      }
    }
  }
  return results
}
