// ── HTML Trend Report Generator ───────────────────────────────
// Produces a self-contained, dark-themed HTML report with inline SVG
// charts from deep-slop scan history records.

import type { HistoryRecord } from '../../history/store.js'
import { APP_VERSION } from '../../version.js'
import {
  HtmlReportOptions,
  escapeHtml,
  scoreClass,
  deltaLabel,
  buildReportStyles,
  buildSummaryCards,
  buildIssueTotals,
  buildPerformance,
  buildEngineUsage,
  buildRecentScans,
} from './helpers.js'
import { buildScoreTrendChart, buildSeverityBreakdownChart, buildSeverityLegend } from './charts.js'

export { HtmlReportOptions } from './helpers.js'

/** Generate a complete HTML trend report string */
export function generateHTMLReport(history: HistoryRecord[], options?: HtmlReportOptions): string {
  const records = history.slice()
  const title = escapeHtml(options?.title ?? 'deep-slop Trend Report')
  const rootDir = escapeHtml(options?.rootDir ?? '.')

  const latest = records[records.length - 1]
  const previous = records.length >= 2 ? records[records.length - 2] : null
  const latestScore = latest ? (latest.score ?? 0) : 0
  const previousScore = previous ? (previous.score ?? 0) : null
  const delta = latest ? deltaLabel(latestScore, previousScore) : '—'
  const totalScans = records.length
  const avgScore = totalScans > 0
    ? Math.round(records.reduce((sum, r) => sum + (r.score ?? 0), 0) / totalScans)
    : 0
  const totalIssues = records.reduce((sum, r) => sum + r.errors + r.warnings + r.info + r.suggestions, 0)
  const avgDuration = totalScans > 0
    ? Math.round(records.reduce((sum, r) => sum + r.durationMs, 0) / totalScans)
    : 0

  const latestClass = scoreClass(latestScore)
  const deltaClass = latest
    ? latestScore > (previousScore ?? latestScore)
      ? 'success'
      : latestScore < (previousScore ?? latestScore)
        ? 'danger'
        : 'muted'
    : 'muted'

  const totalIssuesBySeverity = records.reduce(
    (acc, r) => {
      acc.errors += r.errors
      acc.warnings += r.warnings
      acc.info += r.info
      acc.suggestions += r.suggestions
      return acc
    },
    { errors: 0, warnings: 0, info: 0, suggestions: 0 },
  )

  const emptyState = '<div class="card empty-state"><h2>No history available</h2><p>Run <code>deep-slop scan</code> to collect trend data.</p></div>'

  const content = totalScans === 0
    ? emptyState
    : `
    ${buildSummaryCards(latestScore, previousScore, avgScore, totalScans, totalIssues, latestClass, deltaClass, delta, previous)}

    <section class="grid cols-2">
      <div class="card">
        <h2>Score Trend</h2>
        ${buildScoreTrendChart(records)}
      </div>
      <div class="card">
        <h2>Severity Breakdown</h2>
        ${buildSeverityBreakdownChart(records)}
        ${buildSeverityLegend()}
      </div>
    </section>

    <section class="grid cols-2">
      ${buildIssueTotals(totalIssuesBySeverity, totalIssues, totalScans)}
      ${buildPerformance(avgDuration, records)}
    </section>

    ${buildEngineUsage(records)}
    ${buildRecentScans(records)}
    `

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${title}</title>
  ${buildReportStyles()}
</head>
<body>
  <div class="container">
    <header>
      <h1>${title}</h1>
      <p>${totalScans} scan${totalScans === 1 ? '' : 's'} &bull; ${rootDir} &bull; Generated by deep-slop v${APP_VERSION}</p>
    </header>

    ${content}

    <footer>
      Generated by <strong>deep-slop v${APP_VERSION}</strong> &bull; ${new Date().toLocaleString('en-US')}
    </footer>
  </div>
</body>
</html>`
}
